### ISSUE TITLE
List headers must be supported. 

### ISSUE THREAD

**Issue by jcustenborder** [jcustenborder/kafka-connect-rabbitmq#25]

**Comment by yangnirinny** [comment]
@jcustenborder Thanks for building this awesome project. Any update on this issue or any tips for resolving this issue?

**Comment by jcustenborder** [comment]
@yangnirinny I just discovered the issue while doing a code review. At this point no one has actually ran into the issue. List headers are rare. Are you hitting this or just asking?

**Comment by yangnirinny** [comment]
Thanks for your reply, @jcustenborder . I might be confused, I am running into this error:
```ERROR Consumer com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer@12efa0fd (amq.ctag-l1Wu4sd16d7O9lzfL-WkNA) method handleDelivery for channel AMQChannel(amqp://user@172.16.1.10:5672/app,1) threw an exception for channel AMQChannel(amqp://user@172.16.1.10:5672/app,1) (com.rabbitmq.client.impl.ForgivingExceptionHandler:124)
org.apache.kafka.connect.errors.DataException: Could not determine the type for field 'x-received-from' type 'java.util.ArrayList'
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.headers(MessageConverter.java:216)
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.basicProperties(MessageConverter.java:239)
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.value(MessageConverter.java:275)
	at com.github.jcustenborder.kafka.connect.rabbitmq.SourceRecordBuilder.sourceRecord(SourceRecordBuilder.java:36)
	at com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer.handleDelivery(ConnectConsumer.java:70)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So I was thinking if this is the issue you posted.

**Comment by jcustenborder** [comment]
OK it looks like you hit the issue I discovered in the code review.

**Comment by yangnirinny** [comment]
@jcustenborder Thanks. I have a question, I am trying to play around this, this is the headers I got from rmq:
```{
	"headers": {
		"x-received-from": {
			"type": "string",
			"timestamp": null,
			"int8": null,
			"int16": null,
			"int32": null,
			"int64": null,
			"float32": null,
			"float64": null,
			"boolean": null,
			"string": "{exchange=web, uri=amqp:///%2F, redelivered=false, cluster-name=rabbit@default},",
			"bytes": null
		}
	}
}```
in line 209 in `MessageConverter.java`, what is the correct format of `headerValue` ?

**Comment by jcustenborder** [comment]
@yangnirinny Give the latest release a shot. I added support for List headers.

**Comment by yangnirinny** [comment]
@jcustenborder Thank you so much for doing this productive fix!! Now I got this:
```
ERROR Consumer com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer@38ee029b (amq.ctag-3Q_VrL6iEXkuZkSt9WPsSw) method handleDelivery for channel AMQChannel(amqp://admin@172.16.1.10:5672/app,1) threw an exception for channel AMQChannel(amqp://admin@172.16.1.10:5672/app,1) (com.rabbitmq.client.impl.ForgivingExceptionHandler:124)
java.lang.ClassCastException: java.util.HashMap cannot be cast to com.rabbitmq.client.LongString
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.headers(MessageConverter.java:217)
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.basicProperties(MessageConverter.java:250)
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.value(MessageConverter.java:286)
	at com.github.jcustenborder.kafka.connect.rabbitmq.SourceRecordBuilder.sourceRecord(SourceRecordBuilder.java:36)
	at com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer.handleDelivery(ConnectConsumer.java:70)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Any more info you need?

**Comment by jcustenborder** [comment]
@yangnirinny Can you help me with a repro of the message or something similar? I tried to create a message using the web interface. This is what gave me the code that is there now.

**Comment by yangnirinny** [comment]
@jcustenborder 
This is a message I get from web interface. Let me know if anything else I can help. Or let me know where I can get a message you need.
```
Exchange | web
Routing Key | app
Properties | headers: x-received-from:
uri:amqp:///%2F
exchange:web
redelivered:false
cluster-name:rabbit@default
Payload | some json
```

**Comment by yangnirinny** [comment]
@jcustenborder I was trying to play with it, but I couldn't get it working. Anything else I can help to reproduce this issue?
