### ISSUE TITLE
Error sending json formatted Kafka messages to RabbitMQ

### ISSUE THREAD

**Issue by xannz** [jcustenborder/kafka-connect-rabbitmq#30]
Hello, I'm trying to send json Kafka messages to RabbitMQ and I've run into the following error:

```
[2018-03-06 10:28:25,997] TRACE current sinkRecord value: {name=john} (com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQSourceTask)
[2018-03-06 10:28:25,997] ERROR Task rabbitmqtest1-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.ConnectException: the value of the record has an invalid type (must be of type byte[])
	at com.github.jcustenborder.kafka.connect.rabbitmq.RabbitMQSinkTask.put(RabbitMQSinkTask.java:54)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:384)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:240)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I see that the sindRecord value is a HashMap `{name=john}` and as such is not a byte[] but I'm not sure how to solve this. The Kafka message value is `{"name": "john"}`.

My worker config is the following:
```
bootstrap.servers=localhost:9092
group.id=testgroup

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.flush.interval.ms=10000
offset.storage.topic=rabbitmq.offsets.1
config.storage.topic=rabbitmq.configs.1
status.storage.topic=rabbitmq.storage.1
config.storage.replication.factor: 1
```

I've rewritten the put method to fit my need, is this the right way to solve this?
```java
  @Override
  public void put(Collection<SinkRecord> sinkRecords) {
    for (SinkRecord record : sinkRecords) {
      log.trace("current sinkRecord value: " + record.value());
      Gson gson = new Gson();
      String json = gson.toJson(record.value());
      try {
        channel.basicPublish(this.config.exchange, this.config.routingKey, null, json.getBytes());
      } catch (IOException e) {
        log.error("There was an error while publishing the outgoing message to RabbitMQ");
        throw new RetriableException(e);
      }
    }
  }
```

**Comment by jcustenborder** [comment]
@xannz In general you should never make changes like this to the connector. Connectors should **always** be independent of format. The reason this connector takes bytes for the key is due to the interface to RabbitMQ. You could for example configure the connector to use the ByteArrayConverter which would pass bytes to the connector. **Keep in mind you can set this at the connector level as well as the worker level.** For example you can just add this to the connector config you are posting to the rest interface. `"key.converter":"org.apache.kafka.connect.converters.ByteArrayConverter", "value.converter":"org.apache.kafka.connect.json.JsonConverter"`

**Comment by xannz** [comment]
@jcustenborder Alright thanks for the clarification!
