### ISSUE TITLE
Error when consuming messages, Invalid value: null used for required field

### ISSUE THREAD

**Issue by mavdi** [jcustenborder/kafka-connect-rabbitmq#5]
Hi,

I've been trying to set this up in our DC/OS cluster. I created a custom docker image with the required jars in class path.

I have `confluent-kafka`, `connector` and `schema-registry` running. After various problems with my lack of understanding of how credentials work, I finally seemed to crack it until this error appeared which I have no idea what it corresponds to.

```
org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:212)
	at org.apache.kafka.connect.data.Struct.validate(Struct.java:232)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:240)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:251)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:215)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:204)
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.basicProperties(MessageConverter.java:224)
	at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.value(MessageConverter.java:256)
	at com.github.jcustenborder.kafka.connect.rabbitmq.SourceRecordBuilder.sourceRecord(SourceRecordBuilder.java:36)
	at com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer.handleDelivery(ConnectConsumer.java:70)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Error appears in many numbers, I assume indicating the messages are being read but having difficulty transferring them?
Any help would be greatly appreciated,

Thanks

**Comment by mavdi** [comment]
OK it seems I would first need to create the schemas mentioned here: https://github.com/jcustenborder/kafka-connect-rabbitmq#schemas

Apologies if that's the case. I will Close and Reopen if necessary.

**Comment by mavdi** [comment]
So, this error appears whenever a message appears with any header value.

**Comment by jcustenborder** [comment]
@mavdi Sorry about the issue. I'm trying to build out a test case for this but I'm unable to repro it. What version are you using?

**Comment by jcustenborder** [comment]
@mavdi Can you try again. I just merged a pull that might have resolved this.
