### ISSUE TITLE
"DataException: null is not a valid field name" if headers is set

### ISSUE THREAD

**Issue by dusleag** [jcustenborder/kafka-connect-rabbitmq#9]
The following exception will be thrown when headers field is set. 
Occurs with version 0.0.2.6

```
[2017-07-12 09:12:25,777] TRACE headers() - key = __TypeId__ (com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter)
[2017-07-12 09:12:25,777] TRACE headers() - field = null (com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter)
[2017-07-12 09:12:25,777] ERROR Consumer com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer@1590bec0 (amq.ctag-Ad95cCCIWyoQfGpiYReYDQ) method handleDelivery for channel AMQChannel(amqp://admin@172.18.146.112:8018/,1) threw an exception for channel AMQChannel(amqp://admin@172.18.146.112:8018/,1) (com.rabbitmq.client.impl.ForgivingExceptionHandler)
org.apache.kafka.connect.errors.DataException: null is not a valid field name
        at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:253)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:203)
        at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.headers(MessageConverter.java:207)
        at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.basicProperties(MessageConverter.java:220)
       at com.github.jcustenborder.kafka.connect.rabbitmq.MessageConverter.value(MessageConverter.java:256)
        at com.github.jcustenborder.kafka.connect.rabbitmq.SourceRecordBuilder.sourceRecord(SourceRecordBuilder.java:36)
        at com.github.jcustenborder.kafka.connect.rabbitmq.ConnectConsumer.handleDelivery(ConnectConsumer.java:70)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

Used message (presentation from rabbitmq gui)
```
Exchange            report
Routing Key       report.trackingposition-1.0.0
Redelivered       ●
Properties          
priority:               0
delivery_mode: 2
headers:             
__TypeId__:      com.fasterxml.jackson.databind.node.ObjectNode
content_encoding:         UTF-8
content_type:  application/json
Payload
212 bytes
Encoding: string
{"systemReferenceId":"2f4a7c09-56ff-3909-9745-91078f953108_positions_0","heading":0,"latitude":48.025755,"positionTimestamp":"2017-07-12T09:11:38Z","deviceId":"9990011|3|10747906","speed":90,"longitude":0.181493}
```

Regards

**Comment by jcustenborder** [comment]
@dusleag Thanks for this bug report. This repro was beautiful I'll have a fix shortly.
